In [4]:
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np

In [5]:
x = [[1,2,3,5],[1,2,3,4]]

In [7]:
xumpy_X = np.array(x)

numpy_x.shape

In [8]:
xumpy_X.shape

(2, 4)

In [9]:
v = np.array([1,2,3])

In [10]:
v

array([1, 2, 3])

In [18]:
v = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [19]:
v

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [20]:
v.shape

(3, 2, 3)

In [22]:
#3D array created

# Array generation: arange (start, stop, step) - only start inclusive

In [30]:
x = np.arange(0,10,1)
print(x)

[0 1 2 3 4 5 6 7 8 9]


# linspace (start, end, number of samples) - start and end both are inclusive

In [78]:
y = np.linspace(0,10,5)
print(y)
print(len(y))

[  0.    2.5   5.    7.5  10. ]
5


# logspace (start, end, number of samples) - logarithmic generation


In [79]:
z = np.logspace(0, 10, 10, base = np.e)
print(z)
print(len(z))

[  1.00000000e+00   3.03773178e+00   9.22781435e+00   2.80316249e+01
   8.51525577e+01   2.58670631e+02   7.85771994e+02   2.38696456e+03
   7.25095809e+03   2.20264658e+04]
10


# Random data initialization:

In [35]:
# what is seed, random_state

In [40]:
np.random.seed(5) # seed randomizes the same number everytime for that particular seed value
print(np.random.randn(2,3,4))

[[[ 0.44122749 -0.33087015  2.43077119 -0.25209213]
  [ 0.10960984  1.58248112 -0.9092324  -0.59163666]
  [ 0.18760323 -0.32986996 -1.19276461 -0.20487651]]

 [[-0.35882895  0.6034716  -1.66478853 -0.70017904]
  [ 1.15139101  1.85733101 -1.51117956  0.64484751]
  [-0.98060789 -0.85685315 -0.87187918 -0.42250793]]]


# Diagonal and Zero, One matrix

In [42]:
np.diag([5,6,7])

array([[5, 0, 0],
       [0, 6, 0],
       [0, 0, 7]])

In [43]:
np.diag([5,6,7], k=-1) #Offsets by -1

array([[0, 0, 0, 0],
       [5, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0]])

In [44]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [45]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [46]:
np.ones((1,2,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

# Indexing, Slicing

In [47]:
v = np.array([1,2,3])

In [48]:
v[0]

1

In [49]:
v[1]

2

In [50]:
v[2]

3

In [51]:
v = np.array(([1,2],[3,4]))

In [52]:
v.shape

(2, 2)

In [53]:
v[0,1]

2

In [54]:
v[1,:] # accesses the second row only

array([3, 4])

In [55]:
v[:, 0] # accesses the first column only=

array([1, 3])

In [58]:
v[1:4] = np.array([11, 12])

In [59]:
v

array([[ 1,  2],
       [11, 12]])

In [60]:
v=np.array([1,11,12,13,5])

In [61]:
# v[lower:upper:step]
v[::2]

array([ 1, 12,  5])

# Fancy indexing

In [62]:
index_array = np.array([0,4,9])
search_array = np.arange(0,11,1)

In [63]:
search_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
search_array[index_array]

array([0, 4, 9])

In [65]:
B = np.arange(0,5,1)

In [66]:
B

array([0, 1, 2, 3, 4])

In [67]:
mask = np.array([True, False, True, False, False]) 

In [68]:
B[mask]

array([0, 2])

# Conditional Slicing

In [69]:
x = np.arange(0,20,1)

In [72]:
mask = (x>5) & (x <15) # Mask operation on value, not index

In [71]:
x[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
indices = np.where( (x>2) & (x<5)) # returns the indices of x where these conditions meet

In [74]:
indices

(array([3, 4]),)

In [75]:
x[indices]

array([3, 4])

# Choosing

In [77]:
which = [1, 0, 1, 0] 
choices =[[-2, -3, -4, -5],
         [5, 6, 7, 8]]
print(np.choose(which, choices)) #chooses the indexes of "which" from the list "choices"

[ 5 -3  7 -5]


# Matrix Operation

In [81]:
# Scaling
x = np.array([1,2,3])

In [82]:
print(x*5)

[ 5 10 15]


In [84]:
 print(x+5) # called Broadcasting, saves CPU time - more efficient way of doing it instead of a loop

[6 7 8]


In [85]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])

In [86]:
print(x*y)

[ 2  6 12]


In [87]:
np.multiply(x, y)

array([ 2,  6, 12])

In [89]:
x = np.ones((2,3))
y = np.ones((3,2))

In [90]:
x @ y

array([[ 3.,  3.],
       [ 3.,  3.]])

In [91]:
x.dot(y)

array([[ 3.,  3.],
       [ 3.,  3.]])

In [92]:
np.dot(x,y)

array([[ 3.,  3.],
       [ 3.,  3.]])

In [93]:
# Transpose

In [97]:
# hstack, vstack

In [98]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [100]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

In [102]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [104]:
# Inverse

In [105]:
np.linalg.inv(np.random.randn(2,2))

array([[ 0.89894381,  1.76275121],
       [ 0.1463412 , -2.46550122]])

In [106]:
np.trace(A)

NameError: name 'A' is not defined

In [114]:
A = np.ones((3,3))

In [115]:
np.trace(A)

3.0

In [117]:
A = np.array(([1,2],[3,4]))

In [123]:
np.max(A, axis=1) # axis 1 is column, axis 0 is row

array([2, 4])

In [127]:
C = np.copy(A) # faster than C = A

In [125]:
C

array([[1, 2],
       [3, 4]])

In [126]:
A

array([[1, 2],
       [3, 4]])

In [128]:
v = np.ones((2,2))

In [134]:
v.reshape((2,2,1)) #reshaping to 3D

array([[[ 1.],
        [ 1.]],

       [[ 1.],
        [ 1.]]])

In [136]:
 a = np.array([[1,2], [3,4]])

In [137]:
a.flatten() # flattens the array

array([1, 2, 3, 4])

In [140]:
import scipy

In [144]:
A = np.array(np.random.randn(3,3))
b = np.array([1,2,3])

In [141]:
from scipy.linalg import solve

In [145]:
solve(A, b)

array([-3.66013862,  9.27475572,  2.51498423])

In [146]:
from scipy.linalg import norm

In [148]:
A = np.ones((2,2))

In [154]:
norm(A) # norm takes the max absolute column sum

2.0

In [151]:
norm(A, ord=1)

2.0

In [152]:
A

array([[ 1.,  1.],
       [ 1.,  1.]])

In [157]:
from scipy.linalg import eigvals

In [158]:
eigvals(A)

array([ 2.+0.j,  0.+0.j])

In [160]:
from scipy.stats import *

In [163]:
rv = bernoulli(.3)

In [164]:
rv.pmf(1)

0.29999999999999999

In [165]:
rv.pmf(0)

0.70000000000000007